### ISSUE TITLE
Shader prob

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [MaysLastPlayGithub/FNF-PsychEngine#31]
### Describe your problem here.

Sorry for bugging Abt shaders again but what does this mean?
[openfl.display.Shader] ERROR: Error compiling fragment shader
ERROR: 0:63: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 0:64: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 2 compilation errors.  No code generated.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by MaysLastPlayGithub** [comment]
That means go edit your frag to make Shader work
