### ISSUE TITLE
AndroidKeyboard ask

### ISSUE THREAD

**Issue by Ajwyunsx** [MaysLastPlayGithub/FNF-PsychEngine#38]
### What is your question?

By the way, how did you make Android Keyboard? Can you tell me the .hx that has too Keyboard? I hope it can be answered
![Screenshot_20230710_233314](https://github.com/MaysLastPlays-FNF-Things/FNF-PsychEngine/assets/107187521/e655771e-4b23-4907-9ea6-d8363068548d)

**Comment by MaysLastPlayGithub** [comment]
FlxG.stage.window.textInputEnabled = true;
