### ISSUE TITLE
hitbox expansion

### ISSUE THREAD

**Issue by Guillermo4060** [MaysLastPlayGithub/FNF-PsychEngine#42]
### What feature do you want to get added on the **base** engine?

I don't know if the space hitbox can be added as in the new versions of the psych engine? As it has 0.7.1h but I would like it to be in 0.6.3

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by moxie-coder** [comment]
this isn't getting updated anymore

**Comment by MaysLastPlayGithub** [comment]
> this isn't getting updated anymore

yea, but maybe I'll decide to update it, idk
