### ISSUE TITLE
Engine keep crashing

### ISSUE THREAD

**Issue by StupidCircle** [MaysLastPlayGithub/FNF-PsychEngine#48]
### Describe your bug here.

I already installed the app, extract the file into .PsychEngine but when i open it, it just appear as a black screen then crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just installed it

**Comment by moxie-coder** [comment]
make sure you enabled permissions for the game, otherwise it will crash
